spring:
  data:
    mongodb:
      host: 'localhost'
      port: 27017
      database: 'jahadi'
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: 'DEBUG'
