package four.group.jahadi.Enums;

public enum MedicalExpertise {

    INNER, INFANT, EAR, ORTHOPEDICS, UROLOGY, RADIOLOGY, SKIN, NERVES, WIFE, EYE,
    SURGERY, INFECTION, PSYCHIATRY, PHYSICAL, PHYSICAL_MEDICINE, SOCIAL_MEDICINE,
    SPORT_MEDICINE

}
