package four.group.jahadi.Models;

public enum ReportType {
    AREAS_PER_PROVINCE,
    MEMBERS_PER_PROVINCE,
    PATIENTS_PER_PROVINCE,
    DRUGS_PER_PROVINCE,
    EXTERNAL_SERVICES_PER_PROVINCE,
    FINANCIAL_EXTERNAL_SERVICES_PER_PROVINCE;
}